# Generated by Django 2.2 on 2019-12-11 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.CharField(max_length=255)),
                ('posted_by', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question_desc', models.TextField()),
                ('question_votes', models.IntegerField(default=0)),
                ('question_img', models.ImageField(blank=True, null=True, upload_to='QuestionImg')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_by', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('answer_desc', models.TextField()),
                ('answer_votes', models.IntegerField(default=0)),
                ('answer_img', models.ImageField(blank=True, null=True, upload_to='AnswerImg')),
                ('is_accept', models.BooleanField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna_app.QuestionModel')),
            ],
        ),
    ]
