# Generated by Django 2.2 on 2019-12-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='titile',
        ),
    ]
