# Generated by Django 2.2.7 on 2019-12-12 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qna_app.CategoryModel'),
            preserve_default=False,
        ),
    ]
