# Generated by Django 2.2 on 2019-12-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0002_remove_questionmodel_titile'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='title',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
